`timescale 1ns / 1ps
`include "riscv_pkg.vh"

module execute_stage (
    // Inputs from Decode/Register File
    input  wire [31:0] pc,            // Current Program Counter
    input  wire [31:0] rs1_data,      // Register 1 Data
    input  wire [31:0] rs2_data,      // Register 2 Data
    input  wire [31:0] imm,           // Sign-Extended Immediate
    
    // Control Signals (Generated by a Control Unit later)
    input  wire        alu_src,       // 0 = rs2_data, 1 = imm
    input  wire [3:0]  alu_ctrl,      // Tells ALU what math to do
    input  wire        branch,        // 1 if this is a branch instruction
    
    // Outputs
    output wire [31:0] alu_result,    // Math Result
    output wire [31:0] branch_target, // Where to jump if we branch
    output wire        pc_src         // 1 if we actually take the branch
);

    // ------------------------------------------------------------------------
    // ALUSrc Multiplexer
    // ------------------------------------------------------------------------
    // Chooses whether the ALU calculates (rs1 + rs2) OR (rs1 + immediate)
    wire [31:0] alu_operand_b = (alu_src) ? imm : rs2_data;

    // ------------------------------------------------------------------------
    // Instantiate the ALU
    // ------------------------------------------------------------------------
    wire zero;
    
    alu alu_inst (
        .a(rs1_data),
        .b(alu_operand_b),
        .alu_ctrl(alu_ctrl),
        .result(alu_result),
        .zero(zero)
    );

    // ------------------------------------------------------------------------
    // Branch Target Adder
    // ------------------------------------------------------------------------
    // Calculate the jump address: PC + Immediate
    assign branch_target = pc + imm;

    // ------------------------------------------------------------------------
    // Branch Decision Logic
    // ------------------------------------------------------------------------
    // If it's a branch instruction AND the ALU math resulted in 0 (e.g., rs1 == rs2)
    assign pc_src = branch & zero;

endmodule